language: python
python: "3.6.3"
matrix:
    include:
        - os: linux
          addons:
            apt:
              sources:
                  - ubuntu-toolchain-r-test
              packages:
                  - gcc-4.9
          env:
              - CC=gcc-4.9
              - CXX=g++-4.9"
        - os: linux
          addons:
            apt:
              sources:
                  - ubuntu-toolchain-r-test
              packages:
                  - gcc-5
          env:
              - CC=gcc-5.0
              - CXX=g++-5.0"
        - os: linux
          addons:
            apt:
              sources:
                  - ubuntu-toolchain-r-test
              packages:
                  - gcc-6
          env:
              - CC=gcc-6.0
              - CXX=g++-6.0"
        - os: linux
          addons:
            apt:
              sources:
                  - ubuntu-toolchain-r-test
              packages:
                  - gcc-7
          env:
              - CC=gcc-7.0
              - CXX=g++-7.0"
        - os: linux
          addons:
            apt:
              sources:
                  - ubuntu-toolchain-r-test
              packages:
                  - gcc-8
          env:
              - CC=gcc-8.0
              - CXX=g++-8.0"
        - os: linux
          addons:
            apt:
              sources:
                  - ubuntu-toolchain-r-test
                  - llvm-toolchain-xenial-3.9
              packages:
                  - clang-3.9
          env:
              - CC=clang-3.9
              - CXX=clang-3.9"
        - os: linux
          dist: xenial
          addons:
            apt:
              sources:
                  - ubuntu-toolchain-r-test
                  - llvm-toolchain-xenial-4.0
              packages:
                  - clang-4.0
          env:
              - CC=clang-4.0
              - CXX=clang-4.0"
        - os: linux
          dist: xenial
          addons:
            apt:
              sources:
                  - ubuntu-toolchain-r-test
                  - llvm-toolchain-xenial-5.0
              packages:
                  - clang-5.0
          env:
              - CC=clang-5.0
              - CXX=clang-5.0"
        - os: linux
          dist: xenial
          addons:
            apt:
              sources:
                  - ubuntu-toolchain-r-test
                  - llvm-toolchain-xenial-6.0
              packages:
                  - clang-6.0
          env:
              - CC=clang-6.0
              - CXX=clang-6.0"
        - os: linux
          dist: xenial
          addons:
            apt:
              sources:
                  - ubuntu-toolchain-r-test
          env:
              - CC=clang-7.0 
              - CXX=clang-7.0"
        - os: macos
          osx_image: xcode7.3
          env:
            - CXX: clang++
            - CC: clang
        - os: macos
          osx_image: xcode8.1
          env:
            - CXX: clang++
            - CC: clang

        - os: macos
          osx_image: xcode9.1
          env:
            - CXX: clang++
            - CC: clang

        - os: macos
          osx_image: xcode10.0
          env:
            - CXX: clang++
            - CC: clang

install:
    - pip3 install conan --upgrade 
    - conan user
script:
    - conan create . LunarWatcher/testing --build missing
