build: false
platform: x86

environment:
    PYTHON: "c:\\Python37"
    PYTHON_VERSION: "3.7.3"
    PYTHON_ARCH: "32"

    
    matrix:
        - MINGW_CONFIGURATIONS: "4.9@x86_64@seh@posix"
        - MINGW_CONFIGURATIONS: "4.9@x86_64@sjlj@posix"
        - MINGW_CONFIGURATIONS: "4.9@x86@sjlj@posix"
        - MINGW_CONFIGURATIONS: "4.9@x86@dwarf2@posix"
        - MINGW_CONFIGURATIONS: "5@x86@dwarf2@posix"
        - MINGW_CONFIGURATIONS: "5@x86_64@seh@posix"
        - MINGW_CONFIGURATIONS: "6@x86@dwarf2@posix"
        - MINGW_CONFIGURATIONS: "6@x86_64@seh@posix"
        - MINGW_CONFIGURATIONS: "7@x86@dwarf2@posix"
        - MINGW_CONFIGURATIONS: "7@x86_64@seh@posix"
        - MINGW_CONFIGURATIONS: "8@x86@dwarf2@posix"
        - MINGW_CONFIGURATIONS: "8@x86_64@seh@posix"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16

install:
    - set PATH=%PATH%;%PYTHON%/Scripts
    - pip.exe install conan
    - conan user

test_script:
    - conan create . LunarWatcher/testing --build missing
